Added shuffleboard and slight refactor
shueja/Monologue pull request #1
Opened 2023-11-12 10:36 UTC by oh-yes-0-fps

Needs testing beyond sim, the shuffleboard semantics are not similar to the rest of the annotations so input is welcome. Also, I need input on how the "level" is supposed to work as it seems to be partially implemented. Also, I propose LogBoth should be deprecated as I can never foresee a situation where you want something on nt and not datalog.

2023-11-13 18:52 UTC, shueja commented
The logging level was a bit of a half-baked feature. 6995 was using the @LogNT annotation to log some driver dashboard stuff, and we hadn’t tested the FMS-connected datalog-only config…

2023-11-13 19:03 UTC, shueja requested changes
Please remove the Shuffleboard stuff and the parts I commented about. Other than that, thanks for the cleanup.

2023-11-13 19:03 UTC, shueja commented on monologue/src/main/java/monologue/MonoRobot.java
I don’t think I’d take this class due to the (IMO) invasiveness of extending from a class instead of implementing an interface (see: Subsystem vs SubsystemBase and the limitations of Java single inheritance)

2023-11-13 19:03 UTC, shueja commented on monologue/src/main/java/monologue/Tracer.java
This class seems out of scope for Monologue. Is it just for benchmarking?

2023-11-15 16:19 UTC, oh-yes-0-fps commented on monologue/src/main/java/monologue/Tracer.java
I usually end up making/reusing a tracer similar to that for each robot I write just to find bottlenecks and I thought it would fit with the whole easier logging theme but I can remove it if you don't like it.

2023-12-03 04:47 UTC, shueja commented
Do you have some kind of documentation for how these new features work and are used? I'm having trouble imagining how usage would differ after this PR is merged.

2023-12-11 04:33 UTC, shueja requested changes

2023-12-11 04:33 UTC, shueja commented on monologue/src/main/java/monologue/LogLevel.java
> +    DEBUG,
Change these:
Remove DEBUG
COMP->OVERRIDE_FILE_ONLY
FILE_IN_COMP->DEFAULT

2023-12-11 04:33 UTC, shueja commented on monologue/src/generate/java/NTLogger.java.jinja
> +                        entry.set(value, timestamp);
The equality checks here and in DataLogger.java.jinja use improper equality comparison. Arrays of objects need to be compared with `Arrays.deepEquals(array1, array2)`, arrays of primitives can be compared with `Arrays.equals(array1, array2)`. Primitives should be compared with `==` and single objects should be compared with `obj1.equals(obj2)` which depends on the `.equals()` override, which is a pretty safe bet for the objects we log.

2023-12-11 04:33 UTC, shueja commented on monologue/src/main/java/monologue/Monologue.java
> +  private static Boolean DEBUG = true;
This flag should be FILE_ONLY and signify the opposite state (i.e. FILE_ONLY being true is equivalent to DEBUG being false)

2023-12-11 04:33 UTC, shueja commented on monologue/src/main/java/monologue/Monologue.java
> +    public MonologueConfig() {}
Fluent builder approach may be overkill for this, not sure.

2023-12-11 18:40 UTC, oh-yes-0-fps commented on monologue/src/main/java/monologue/Monologue.java
> +    public MonologueConfig() {}
I collapsed Lazy NT and Lazy File into one boolean because there was no way to differentiate due to how NT is sent to Datalog. This allowed me to have a few enough args to just make it a function call with no config class.

2023-12-15 23:55 UTC, shueja approved these changes

2023-12-16 00:06 UTC, merged