Huge cleanup, error handling improvements and configurability improvements
shueja/Monologue pull request #21
Opened 2024-03-31 19:41 UTC by oh-yes-0-fps

This has a variety of changes in it and I'm sorry about that, I tried to keep them separated but they depended upon eachother too heavily that it would have been messy and more work.

This pr has:
- Cleaning up across the entire lib
- Better type error handling
- Better configuration of behavior
- A way to run Monologue in full robot unit tests
- A MonoDashboard class to use Monologue from anywhere in the code
- A fix for overlapping NT datalog subsrciptions and other libs

2024-04-24 02:49 UTC, oh-yes-0-fps commented
Here is an example of setting up Monologue under the new system
[2024 dev robot code](https://github.com/McQuaidRobotics/2024_Crescendo/blob/development/src/main/java/com/igknighters/Robot.java#L137)

Monodashboard example ig although its pretty self explanatory
[MonoDashboard](https://github.com/McQuaidRobotics/2024_Crescendo/blob/development/src/main/java/com/igknighters/GlobalState.java#L362)

2024-04-24 02:50 UTC, oh-yes-0-fps commented
Also error messages have been massively improved, I would still like to do compile time type checking but if were doing annotation processor for that might as well do what epilogue does

2024-04-24 03:08 UTC, shueja requested changes
My biggest concern is the loss of NTSendable file logging. I don't consider that an acceptable feature removal, even though the implementation was somewhat separate from the file-only features, etc.

2024-04-24 03:08 UTC, shueja commented on monologue/src/generate/java/MonoDashboard.java.jinja
> +  public static void put(String entryName, {{t.java.ValueType}} value) {
Why are the user-facing methods called `put` here and `log` in Logged?
Also MonoDashboard as a separate class isn't a great name or design for discoverability IMO; I would prefer these be under Monologue.java if that didn't mean making that a Jinja templat

2024-04-24 03:16 UTC, shueja commented on monologue/src/main/java/monologue/EvalField.java
> +        MonologueLog.runtimeWarn(
Even though the implementation is not file-only, the logging should still be done, and the warning can explain why it's still on NT.

2024-04-24 03:37 UTC, oh-yes-0-fps commented on monologue/src/main/java/monologue/EvalField.java
> +        MonologueLog.runtimeWarn(
Why use @Log.File tho? just use @Log or @Log.NT, allowing @Log.File is just a lie and will cause confusion

2024-04-24 03:39 UTC, oh-yes-0-fps commented on monologue/src/generate/java/MonoDashboard.java.jinja
> +  public static void put(String entryName, {{t.java.ValueType}} value) {
`put` implies the location matters more and it doesn't behave the same with the path as `log`, I originally had it in Monolgue but faced the same issue you said, which also bloated Monologue a lot.

2024-04-24 03:41 UTC, oh-yes-0-fps commented on monologue/src/main/java/monologue/MonologueLog.java
> +    DataLogManager.logNetworkTables(false);
I will expand upon docs of the effects this has but this is needed for custom prefixes and not accidentally dual logging things.

2024-04-24 03:43 UTC, oh-yes-0-fps commented on monologue/src/main/java/monologue/EvalMethod.java
> +    if (Modifier.isStatic(method.getModifiers())) {
We talked about this in discord, we decided not to have any annotation support for static members. This was always behaving weird and is just explicitly disallowed now.

2024-04-24 03:44 UTC, oh-yes-0-fps commented on monologue/src/main/java/monologue/EvalMethod.java
> +                + " supllier is erroring: "
The stack trace for runtime warning wouldnt be useful to the user, it would always say it was inside the monologue library which is already made clear by the error message.

2024-04-24 03:46 UTC, oh-yes-0-fps commented on monologue/src/generate/java/MonoDashboard.java.jinja
> +  public static void put(String entryName, {{t.java.ValueType}} value) {
Monodashboard can be added as references to docs in a lot of places so hopefully its more discoverable via that and the wiki when that's updated.

2024-05-20 05:09 UTC, shueja requested changes

2024-05-20 05:09 UTC, shueja commented on monologue/src/main/java/monologue/EvalField.java
> +            "NTSendable isn't supported for file logging: " + rootPath + "." + field.getName());
```suggestion
            "NTSendable isn't supported for @Log.File, use @Log or @Log.NT instead: " + rootPath + "." + field.getName());

```

2024-05-20 05:09 UTC, shueja commented on monologue/src/main/java/monologue/EvalField.java
> +    return;
Unnecessary return statement
```suggestion
```

2024-05-20 05:09 UTC, shueja commented on monologue/src/main/java/monologue/EvalMethod.java
> +        MonologueLog.runtimeWarn(
In my experience this warning is just console spam with no guide for what to fix, but IDK how to improve the message.

2024-05-20 05:09 UTC, shueja commented on monologue/src/main/java/monologue/Monologue.java
> +    // we need to make sure we never log network tables through the implicit wpilib logger
what happens if a user or other library turns this back on?

2024-05-20 05:09 UTC, shueja commented on monologue/src/main/java/monologue/Monologue.java
> +            "fileOnly cannot be null in MonologueConfig, falling back to false");
```suggestion
            "fileOnly cannot be null in MonologueConfig, falling back to false (always log NT)");

```

2024-05-20 05:13 UTC, oh-yes-0-fps commented on monologue/src/main/java/monologue/EvalMethod.java
> +        MonologueLog.runtimeWarn(
I've personally never had it happen, I would have assumed the `e.toString` provides insight to the error. Silently failing IMO is worse and it does provide a path to what is causing a problem.

2024-05-20 05:15 UTC, oh-yes-0-fps commented on monologue/src/main/java/monologue/Annotations.java
> +   * the object this field is in. This is useful for flattening complex objects into a single path.
I actually don't know what name collisions do, probably some UB depending on if the types match or not.

2024-05-20 05:16 UTC, oh-yes-0-fps commented on monologue/src/generate/java/NTLogger.java.jinja
> +        // NetworkTablesJNI.startEntryDataLog(NetworkTableInstance.getDefault().getHandle(), DataLogManager.getLog(), path, "NT:" + path);
I suppose i meant to delete it

2024-05-20 05:18 UTC, oh-yes-0-fps commented on monologue/src/generate/java/GlobalLogged.java.jinja
> + * The GlobalLogged class is a utility class that provides a simple way to use Monologue's
The user will actually never see the class docs, the `.log(...)` docs say its an absolute path, didn't know if that was enough or not.

2024-05-20 05:24 UTC, oh-yes-0-fps commented on monologue/src/generate/java/GenericLogger.java.jinja
> +      if (componentType.equals(Byte.class)) {
ummmm, idr there was 100% a reason it was like a month ago tho :3

2024-05-20 05:24 UTC, oh-yes-0-fps commented on monologue/src/generate/java/GenericLogger.java.jinja
> +  public Class<?> simplfyPrimTypes(Class<?> type) {
silly me oh my

2024-05-20 05:30 UTC, oh-yes-0-fps commented on monologue/src/generate/java/GenericLogger.java.jinja
> +      if (componentType.equals(Byte.class)) {
i think simplifying the component type would work? tbh I have a hard time with boxed type semantics and casting.

2024-05-20 05:40 UTC, oh-yes-0-fps commented on monologue/src/generate/java/DataLogger.java.jinja
> +    private static class NTIntegerArrayLogEntry extends DataLogEntry {
Removed

2024-05-20 05:40 UTC, oh-yes-0-fps commented on monologue/src/generate/java/GenericLogger.java.jinja
> +      if (componentType.equals(Byte.class)) {
Added a simplifyType to the component type and it worked

2024-05-20 05:44 UTC, oh-yes-0-fps commented on monologue/src/main/java/monologue/Annotations.java
> +   * the object this field is in. This is useful for flattening complex objects into a single path.
It wasnt even implemented, i'm removing it for now. I'll add it back in a future pr when I get the motivation as it is something I could use.

2024-05-20 05:44 UTC, shueja approved these changes

2024-05-20 05:45 UTC, merged

2024-05-20 05:45 UTC, oh-yes-0-fps commented
Holy smokes